services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    container_name: ollama-app
    restart: always
    depends_on:
      ollama-demo:
        condition: service_healthy
      ollama-pull-demo:
        condition: service_completed_successfully
    networks:
      - ollama-docker
  
  ollama-demo:
    volumes:
      - ./models/ollama:/root/.ollama
    container_name: ollama-demo
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    healthcheck:
      test: ollama --version || exit 1
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  ollama-pull-demo:
    image: docker/genai:ollama-pull
    container_name: ollama-pull-demo
    depends_on:
      ollama-demo:
        condition: service_healthy
    environment:
      OLLAMA_BASE_URL: http://ollama-demo:11434
      LLM: llama2
    networks:
      - ollama-docker

networks:
  ollama-docker:
    driver: bridge
