services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    container_name: ollama-app
    restart: always
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama-docker
  
  ollama:
    volumes:
      - ./models/ollama:/root/.ollama
      - ./entrypoint-ollama.sh:/entrypoint-ollama.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    healthcheck:
      test: ollama --version || exit 1
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    entrypoint: ["/usr/bin/bash", "/entrypoint-ollama.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  ollama-docker:
    driver: bridge
